FROM node:12.16.3-alpine

WORKDIR /root/Capstone/Project/Backend
COPY package*.json ./

RUN npm install -g npm@7.6.3
RUN npm install
ENV NODE_ENV development

COPY . .

CMD ["npm", "run", "swagger"]
